# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(929, 566)
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush)
        brush1 = QBrush(QColor(238, 238, 236, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        MainWindow.setPalette(palette)
        font = QFont()
        font.setFamily(u"Bitstream Vera Sans Mono")
        MainWindow.setFont(font)
        icon = QIcon()
        icon.addFile(u"src/modbus/modbus/picture/teco_icon.png", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolButtonStyle(Qt.ToolButtonIconOnly)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayoutWidget = QWidget(self.centralwidget)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(20, 110, 203, 381))
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.btn_reset = QPushButton(self.verticalLayoutWidget)
        self.btn_reset.setObjectName(u"btn_reset")
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush2 = QBrush(QColor(218, 119, 0, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        self.btn_reset.setPalette(palette1)
        font1 = QFont()
        font1.setFamily(u"Bitstream Vera Sans")
        font1.setPointSize(16)
        font1.setBold(True)
        font1.setWeight(75)
        self.btn_reset.setFont(font1)
        self.btn_reset.setStyleSheet(u"background-color:#da7700;color:white;border-color: black;")

        self.verticalLayout.addWidget(self.btn_reset)

        self.btn_enable = QPushButton(self.verticalLayoutWidget)
        self.btn_enable.setObjectName(u"btn_enable")
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush3 = QBrush(QColor(0, 210, 26, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.Button, brush3)
        palette2.setBrush(QPalette.Active, QPalette.Text, brush)
        palette2.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette2.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette2.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Button, brush3)
        palette2.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Base, brush3)
        palette2.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.Button, brush3)
        palette2.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette2.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        self.btn_enable.setPalette(palette2)
        self.btn_enable.setFont(font1)
        self.btn_enable.setStyleSheet(u"background-color:#00d21a;color:white;border-color: black;")

        self.verticalLayout.addWidget(self.btn_enable)

        self.btn_disable = QPushButton(self.verticalLayoutWidget)
        self.btn_disable.setObjectName(u"btn_disable")
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush4 = QBrush(QColor(177, 0, 17, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Active, QPalette.Button, brush4)
        palette3.setBrush(QPalette.Active, QPalette.Text, brush)
        palette3.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette3.setBrush(QPalette.Active, QPalette.Base, brush4)
        palette3.setBrush(QPalette.Active, QPalette.Window, brush4)
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Button, brush4)
        palette3.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Base, brush4)
        palette3.setBrush(QPalette.Inactive, QPalette.Window, brush4)
        palette3.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.Button, brush4)
        palette3.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.Base, brush4)
        palette3.setBrush(QPalette.Disabled, QPalette.Window, brush4)
        self.btn_disable.setPalette(palette3)
        self.btn_disable.setFont(font1)
        self.btn_disable.setStyleSheet(u"background-color:#b10011;color:white;border-color: black;")

        self.verticalLayout.addWidget(self.btn_disable)

        self.onBtn = QPushButton(self.verticalLayoutWidget)
        self.onBtn.setObjectName(u"onBtn")
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette4.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette4.setBrush(QPalette.Active, QPalette.Text, brush)
        palette4.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette4.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette4.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette4.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette4.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette4.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette4.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette4.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette4.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette4.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette4.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette4.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        self.onBtn.setPalette(palette4)
        self.onBtn.setFont(font1)
        self.onBtn.setStyleSheet(u"background-color:#da7700;color:white;border-color: black;")

        self.verticalLayout.addWidget(self.onBtn)

        self.offBtn = QPushButton(self.verticalLayoutWidget)
        self.offBtn.setObjectName(u"offBtn")
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette5.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette5.setBrush(QPalette.Active, QPalette.Text, brush)
        palette5.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette5.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette5.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette5.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette5.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette5.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette5.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette5.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette5.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette5.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette5.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette5.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        self.offBtn.setPalette(palette5)
        self.offBtn.setFont(font1)
        self.offBtn.setStyleSheet(u"background-color:#da7700;color:white;border-color: black;")

        self.verticalLayout.addWidget(self.offBtn)

        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(220, 10, 691, 501))
        font2 = QFont()
        font2.setFamily(u"Bitstream Vera Sans Mono")
        font2.setBold(True)
        font2.setWeight(75)
        self.tabWidget.setFont(font2)
        self.tabWidget.setTabShape(QTabWidget.Triangular)
        self.tab_arm = QWidget()
        self.tab_arm.setObjectName(u"tab_arm")
        self.lineEdit_ip_2 = QLineEdit(self.tab_arm)
        self.lineEdit_ip_2.setObjectName(u"lineEdit_ip_2")
        self.lineEdit_ip_2.setGeometry(QRect(20, 40, 91, 26))
        self.lineEdit_ip_3 = QLineEdit(self.tab_arm)
        self.lineEdit_ip_3.setObjectName(u"lineEdit_ip_3")
        self.lineEdit_ip_3.setGeometry(QRect(20, 80, 91, 26))
        self.tabWidget.addTab(self.tab_arm, "")
        self.tab_mission = QWidget()
        self.tab_mission.setObjectName(u"tab_mission")
        self.tabWidget.addTab(self.tab_mission, "")
        self.tab_state = QWidget()
        self.tab_state.setObjectName(u"tab_state")
        self.tabWidget.addTab(self.tab_state, "")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_other = QWidget()
        self.tab_other.setObjectName(u"tab_other")
        self.label_arm_picture = QLabel(self.tab_other)
        self.label_arm_picture.setObjectName(u"label_arm_picture")
        self.label_arm_picture.setGeometry(QRect(20, 80, 151, 141))
        self.label_arm_picture.setPixmap(QPixmap(u"../picture/teco_arm.png"))
        self.label_arm_picture.setScaledContents(True)
        self.label_arm_gif = QLabel(self.tab_other)
        self.label_arm_gif.setObjectName(u"label_arm_gif")
        self.label_arm_gif.setGeometry(QRect(30, 280, 151, 141))
        self.label_arm_gif.setPixmap(QPixmap(u"src/modbus/modbus/picture/teco_arm.png"))
        self.label_arm_gif.setScaledContents(True)
        self.tabWidget.addTab(self.tab_other, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 929, 23))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Control Window", None))
        self.btn_reset.setText(QCoreApplication.translate("MainWindow", u"Dynamics", None))
        self.btn_enable.setText(QCoreApplication.translate("MainWindow", u"Dynamics Space", None))
        self.btn_disable.setText("")
        self.onBtn.setText(QCoreApplication.translate("MainWindow", u"Read state", None))
        self.offBtn.setText(QCoreApplication.translate("MainWindow", u"Read off", None))
#if QT_CONFIG(whatsthis)
        self.tabWidget.setWhatsThis(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>dd</p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.lineEdit_ip_2.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.lineEdit_ip_3.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_arm), QCoreApplication.translate("MainWindow", u"Kinematics", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_mission), QCoreApplication.translate("MainWindow", u"Dynamics", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_state), QCoreApplication.translate("MainWindow", u"Dynamics Space", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Arm Data", None))
        self.label_arm_picture.setText("")
        self.label_arm_gif.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_other), QCoreApplication.translate("MainWindow", u"Other", None))
    # retranslateUi

